version: "3.5"

services:

  beanstalkd:
    image: schickling/beanstalkd
    platform: linux/x86_64
    restart: always
    ports:
      - '11300:11300'
    volumes:
      - beanstalkd_binlog:/my-binlog
    command: '-b /my-binlog'

  redis_rdb:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis-conf/redis_rds/redis.conf:/opt/bitnami/redis/etc/redis.conf'
    ports:
      - '6379:6379'

  redis_aof:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis-conf/redis_aof/redis.conf:/opt/bitnami/redis/etc/redis.conf'
    ports:
      - '6380:6379'

  redis_rds_aof:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis-conf/redis_rds_aof/redis.conf:/opt/bitnami/redis/etc/redis.conf'
    ports:
      - '6381:6379'

  redis_no_persistence:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis-conf/redis_no_persistence/redis.conf:/opt/bitnami/redis/etc/redis.conf'
    ports:
      - '6382:6379'

  php-producers:
    image: php:8.1-fpm
    depends_on:
      - beanstalkd
      - redis_rdb
      - redis_aof
      - redis_no_persistence
      - redis_rds_aof
    volumes:
      - './php:/usr/src/myapp'
    working_dir: /usr/src/myapp
    entrypoint: php send.php

  php-consumer:
    image: php:8.1-fpm
    depends_on:
      - beanstalkd
      - redis_rdb
      - redis_aof
      - redis_no_persistence
      - redis_rds_aof
    volumes:
      - './php:/usr/src/myapp'
    working_dir: /usr/src/myapp
    entrypoint: php worker.php



volumes:
  beanstalkd_binlog: {}
